#! /usr/bin/python -tt
# coding=utf-8
#
"""gen_removal - Generate org-mode compatible cues from package.mask"""
# Copyright (C) 2010-2011  James Rowe;
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

__version__ = "0.2.0"
__date__ = "2011-03-07"
__author__ = "James Rowe <jnrowe@gmail.com>"
__copyright__ = "Copyright (C) 2010-2011  James Rowe"
__license__ = "GNU General Public License Version 3"
__credits__ = ""
__history__ = "See Git repository"

import collections
import datetime
import glob
import os
import re
import sys

def main():
    pmask = "profiles/package.mask"
    if not os.path.exists(pmask):
        sys.stderr.write("%s must be run from within a repo.\n" % __file__)
        return 1

    chunks = open("profiles/package.mask").read().split("\n\n")
    removals = collections.defaultdict(list)
    for chunk in filter(lambda s: "\n# X-Removal: " in s, chunks):
        data = chunk[chunk.index("X-Removal"):].split("\n")
        removal_date = datetime.datetime.strptime(data[0][11:], "%Y-%m-%d")
        removals[removal_date].append(data[1:])

    with open("support/removal.org", "w") as file:
        file.write("* THIS FILE IS AUTOGENERATED FROM profiles/package.mask\n\n")
        for date, items in sorted(removals.items(), reverse=True):
            for pkgs in items:
                for pkg in pkgs:
                    file.write("** %s SCHEDULED: <%s>\n"
                               % (pkg, date.strftime("%Y-%m-%d %a")))

if __name__ == '__main__':
    sys.exit(main())
