language: python
python:
  - 2.7
before_install:
install:
  - pip install -r support/requirements-doc.txt
script:
  - sphinx-build -n -W -b html -d build/sphinx/doctrees doc build/sphinx/html
branches:
  except:
    - /^play\/.*$/
