from collections import defaultdict
from datetime import datetime

from cake.helpers import task
from cake.lib import puts

from utils import dep


@task('Generate org-mode file for package removals')
@dep(['support/removal.org', ], ['profiles/package.mask', ])
def gen_removals():
    chunks = open("profiles/package.mask").read().split("\n\n")
    removals = defaultdict(list)
    for chunk in filter(lambda s: "\n# X-Removal: " in s, chunks):
        data = chunk[chunk.index("X-Removal"):].split("\n")
        removal_date = datetime.strptime(data[0][11:], "%Y-%m-%d")
        removals[removal_date].append(data[1:])

    with open("support/removal.org", "w") as file:
        file.write("* THIS FILE IS AUTOGENERATED FROM "
                   "profiles/package.mask\n\n")
        for date, items in sorted(removals.items(), reverse=True):
            for pkgs in items:
                for pkg in pkgs:
                    file.write("** %s SCHEDULED: <%s>\n"
                               % (pkg, date.strftime("%Y-%m-%d %a")))
    puts('{green}removal.org generated!')
