--- !ditz.rubyforge.org,2008-03-06/project 
name: misc-overlay
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: misc-overlay
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: current
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-02-10 21:19:49.379803 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - This is the only release currently hosted on GitHub.
